// -*- C++ -*-
//
// generated by wxGlade
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//  Dialog1.cpp Frame1.cpp
//

#ifndef PREFERENCES_H
#define PREFERENCES_H

#include <wx/image.h>
#include <wx/wx.h>

// begin wxGlade: ::dependencies
#include <wx/slider.h>
#include <wx/spinctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade

class PreferencesWindow : public wxDialog {
public:
    // begin wxGlade: PreferencesWindow::ids
    // end wxGlade

    PreferencesWindow(wxWindow* parent, wxWindowID id, const wxString& title,
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE);

private:
protected:
    // begin wxGlade: PreferencesWindow::attributes
    wxTextCtrl* server;
    wxTextCtrl* port;
    wxTextCtrl* api_key;
    wxSpinCtrlDouble* sendGetRequestTime;
    wxStaticText* last_connection;
    wxStaticText* connection_status;
    // Controls for the integer radius
    wxSpinCtrl* radius_spin;
    wxSlider* radius_slider;
    wxButton* button_SAVE;
    wxButton* button_CANCEL;
    // end wxGlade
}; // wxGlade: end class

#endif // PREFERENCES_H