// -*- C++ -*-
//
// generated by wxGlade
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//  Dialog1.cpp Frame1.cpp
//

#include "preferences.h"

// begin wxGlade: ::extracode
// end wxGlade

// Define constants for the radius constraints
const int MIN_RADIUS = 2500;
const int MAX_RADIUS = 10000;
const int DEFAULT_RADIUS = 5000;

PreferencesWindow::PreferencesWindow(wxWindow* parent, wxWindowID id,
    const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: PreferencesWindow::PreferencesWindow
    SetTitle(wxT("Intention Drawing Settings"));
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);

    // Reduced number of rows needed, but keeping dynamic sizing via
    // AddGrowableRow
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(10, 2, 5, 5);
    sizer_1->Add(grid_sizer_1, 0, wxALL | wxEXPAND, 10);

    // --- Server Name (Retained) ---
    wxStaticText* label_1
        = new wxStaticText(this, wxID_ANY, wxT("Server URL:"));
    grid_sizer_1->Add(label_1, 0, 0, 0);
    server = new wxTextCtrl(this, wxID_ANY, wxT("google.com"));
    server->SetMinSize(wxSize(300, 32));
    grid_sizer_1->Add(server, 0, 0, 0);

    // --- Port (Retained) ---
    wxStaticText* label_2 = new wxStaticText(this, wxID_ANY, wxT("Port:"));
    grid_sizer_1->Add(label_2, 0, 0, 0);
    port = new wxTextCtrl(this, wxID_ANY, wxT("443"));
    grid_sizer_1->Add(port, 0, 0, 0);

    // --- API Key (Retained) ---
    wxStaticText* label_13 = new wxStaticText(this, wxID_ANY, wxT("API key:"));
    grid_sizer_1->Add(label_13, 0, 0, 0);

    api_key = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    api_key->SetMinSize(wxSize(300, 32));
    grid_sizer_1->Add(api_key, 1, wxEXPAND, 0);

    // --- GET Request Send Delay (Retained) ---
    wxStaticText* label_3
        = new wxStaticText(this, wxID_ANY, wxT("GET Request Send Delay (s):"));
    grid_sizer_1->Add(label_3, 0, 0, 0);
    sendGetRequestTime = new wxSpinCtrlDouble(this, wxID_ANY, wxT("10.0"),
        wxDefaultPosition, wxDefaultSize, wxSP_ARROW_KEYS, 0.0, 100000.0);
    sendGetRequestTime->SetDigits(0);
    grid_sizer_1->Add(sendGetRequestTime, 0, 0, 0);

    // --- Last connection (Retained) ---
    wxStaticText* label_5
        = new wxStaticText(this, wxID_ANY, wxT("Last connection:"));
    grid_sizer_1->Add(label_5, 0, 0, 0);
    last_connection
        = new wxStaticText(this, wxID_ANY, wxT("2024-12-24 00:00:00"));
    grid_sizer_1->Add(last_connection, 0, 0, 0);

    // --- Connection Status (Retained) ---
    grid_sizer_1->Add(20, 20, 0, 0, 0); // Spacer
    connection_status = new wxStaticText(this, wxID_ANY, wxT("Not connected"));
    grid_sizer_1->Add(connection_status, 0, 0, 0);

    // --- Radius (int with slider) (Retained) ---
    wxStaticText* label_new_radius
        = new wxStaticText(this, wxID_ANY, wxT("Radar Range/Radius:"));
    grid_sizer_1->Add(label_new_radius, 0, 0, 0);

    wxBoxSizer* sizer_radius = new wxBoxSizer(wxHORIZONTAL);

    // Spin control: Min=2500, Max=10000, Initial=5000
    radius_spin = new wxSpinCtrl(this, wxID_ANY,
        wxString::Format(wxT("%d"), DEFAULT_RADIUS), wxDefaultPosition,
        wxDefaultSize, wxSP_ARROW_KEYS, MIN_RADIUS, MAX_RADIUS, DEFAULT_RADIUS);
    sizer_radius->Add(radius_spin, 0, wxRIGHT, 5);

    // Slider: Min=2500, Max=10000, Initial=5000
    radius_slider
        = new wxSlider(this, wxID_ANY, DEFAULT_RADIUS, MIN_RADIUS, MAX_RADIUS,
            wxDefaultPosition, wxSize(200, -1), wxSL_HORIZONTAL | wxSL_LABELS);
    sizer_radius->Add(radius_slider, 1, wxEXPAND, 0);

    grid_sizer_1->Add(sizer_radius, 1, wxEXPAND, 0);

    // --- Unsent datapoints and Unsent tracks (REMOVED) ---

    // --- Dialog Buttons ---
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(sizer_2, 0, wxALIGN_RIGHT | wxALL, 4);
    button_SAVE = new wxButton(this, wxID_SAVE, wxEmptyString);
    button_SAVE->SetDefault();
    sizer_2->Add(button_SAVE, 0, 0, 0);
    button_CANCEL = new wxButton(this, wxID_CANCEL, wxEmptyString);
    sizer_2->Add(button_CANCEL, 0, 0, 0);

    // Update growable rows/cols.
    // The total number of content rows is now 7.
    grid_sizer_1->AddGrowableRow(0);
    grid_sizer_1->AddGrowableRow(1);
    grid_sizer_1->AddGrowableRow(2); // API Key row
    grid_sizer_1->AddGrowableRow(4); // Last connection row
    grid_sizer_1->AddGrowableRow(5); // Connection status row
    grid_sizer_1->AddGrowableRow(6); // Radius row
    grid_sizer_1->AddGrowableCol(0);
    grid_sizer_1->AddGrowableCol(1);

    SetSizer(sizer_1);
    sizer_1->Fit(this);
    SetAffirmativeId(button_SAVE->GetId());
    SetEscapeId(button_CANCEL->GetId());

    Layout();
    // end wxGlade
}